[project]
name = "registrabids"
version = "0.1.0"
description = "BIDS registration pipeline using ANTs"
requires-python = ">=3.10"
license = {text = "GPL-3.0-or-later"}

dependencies = [
    "numpy",
    "nibabel",
    "pybids",
    "click"
]

[project.scripts]
registrabids = "registration.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["registrabids*"]

[tool.setuptools.package-data]
registrabids = ["resources/**/*.nii.gz", "resources/**/*.tsv"]

[feature.dev.dependencies]
pre-commit = "*"
ruff = ">=0.11"

[feature.dev.tasks]
lint = "ruff check registrabids/"
